name: stib-waittime-source
language: Python
variables:
  - name: output
    inputType: OutputTopic
    defaultValue: waittime
    required: false
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
